spring:
 application:
  name: eureka
server:
  port: 9521
eureka:
  instance:
    hostname: 127.0.0.1
#    leaseRenewalIntervalInSeconds: 5
#    leaseExpirationDurationInSeconds: 5
  client:
   registerWithEureka: false
   fetchRegistry: false
   serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/